In [1]:
import numpy as np
float_formatter = "{:.3f}".format
np.set_printoptions(formatter={'float_kind':float_formatter})

Homogeneous Datatype

In [2]:
# l1 = ['a', 56, 12.48]
l1 = [56, 12.358]
print(l1)
na1 = np.array(l1)
# print(na1)
na1

[56, 12.358]


array([56.000, 12.358])

In [3]:
array1 = np.array([1,2,3,4.4], dtype='i')
# Create Numpy array of list [1,2,3,4] of datatype int
print(array1)

array2 = np.array([1,2,3,4,5], dtype='f')
print(array2)

[1 2 3 4]
[1.000 2.000 3.000 4.000 5.000]


Arrays support element-wise operation

In [4]:
arr = np.array([1,2,3,4])
print(arr, arr*2)
print(np.multiply(arr, arr*2))
print(np.multiply(arr, 2))
arr2 = np.array([3,5,2,6])
print(np.add(arr, arr2))

[1 2 3 4] [2 4 6 8]
[ 2  8 18 32]
[2 4 6 8]
[ 4  7  5 10]


In [5]:
# Array to List
arr = np.array([1,2,3])
print(type(arr))

li = list(arr)
print(type(li), li)

<class 'numpy.ndarray'>
<class 'list'> [1, 2, 3]


In [6]:
mat = np.array([[10, 34, 45],[125, 874, 87]], dtype='f')
print(mat)

arr_tup = np.array((34, 56, 23))
print(arr_tup)

[[10.000 34.000 45.000]
 [125.000 874.000 87.000]]
[34 56 23]


In [7]:
arr = np.arange(0, 7, 1)
print(arr)

arr2 = np.arange(0, 6, 1, dtype='f')
print(arr2)

arr_char = np.array(range(6), dtype='U')
print(arr_char)

[0 1 2 3 4 5 6]
[0.000 1.000 2.000 3.000 4.000 5.000]
['0' '1' '2' '3' '4' '5']


In [8]:
ones_arr = np.ones(5)
print(ones_arr)

ones_mat1 = np.ones((2, 4))
print(ones_mat1)

ones_mat2 = np.ones((2, 4, 6), dtype='i')
print(ones_mat2)

ones_mat3 = np.ones((2, 3), dtype='i')
print(ones_mat3)

# Similar for np.zeros
zeros_mat = np.zeros((3, 5), dtype='i')
print(zeros_mat)

[1.000 1.000 1.000 1.000 1.000]
[[1.000 1.000 1.000 1.000]
 [1.000 1.000 1.000 1.000]]
[[[1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]]

 [[1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]]]
[[1 1 1]
 [1 1 1]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


```
Dimension reading is done from RIGHT to LEFT
```

In [9]:
random_arr = np.random.random((3))
print(random_arr)

random_mat = np.random.random((3, 6))
print(random_mat)

random_mat2 = np.random.random((3,6,3))
print(random_mat2)

[0.777 0.329 0.303]
[[0.203 0.375 0.040 0.282 0.583 0.659]
 [0.437 0.468 0.025 0.343 0.376 0.003]
 [0.192 0.250 0.509 0.081 0.927 0.384]]
[[[0.069 0.173 0.845]
  [0.381 0.672 0.760]
  [0.557 0.792 0.966]
  [0.679 0.460 0.842]
  [0.180 0.721 0.145]
  [0.679 0.799 0.449]]

 [[0.949 0.662 0.676]
  [0.511 0.865 0.275]
  [0.336 0.674 0.961]
  [0.205 0.212 0.149]
  [0.995 0.725 0.011]
  [0.873 0.049 0.876]]

 [[0.121 0.387 0.920]
  [0.094 0.079 0.774]
  [0.505 0.265 0.730]
  [0.693 0.998 0.299]
  [0.632 0.015 0.770]
  [0.622 0.813 0.710]]]


In [10]:
print(np.random.randint(10, 25, size=(5, 6)))

[[14 18 19 21 16 22]
 [24 23 24 22 14 10]
 [11 23 22 23 11 20]
 [21 13 13 12 24 10]
 [16 21 13 20 21 23]]


In [11]:
print(np.linspace(1, 10, 4))
print(np.linspace(10, 20, 6))

[1.000 4.000 7.000 10.000]
[10.000 12.000 14.000 16.000 18.000 20.000]


In [12]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([[1,2,3],[4,5,6]])
arr3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]], 
                [[1,2,3],
                [4,5,6],
                [7,8,9]]])
print(arr3)
print(arr1.shape, arr2.shape, arr3.shape)
print(arr1.ndim, arr2.ndim, arr3.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(4,) (2, 3) (2, 3, 3)
1 2 3


In [13]:
arr1 = np.array([10, 32, 36, 34, 4, 55])

reshaped_arr1 = arr1.reshape(3, 2)
# reshaped_arr1 = arr1.reshape(3, 3) # gives error as it has only 6 elements and 3x3 must have 3 elements
print(reshaped_arr1)

arr2 = np.array([[10, 32, 36],[34, 4, 56]])
reshaped_arr2 = arr2.reshape(6)
print(reshaped_arr2)

arr3 = np.array([[10, 32, 36, 34],[56,19,75,20]])
reshaped_arr3 = arr3.reshape(2,2,2)
print(reshaped_arr3)

[[10 32]
 [36 34]
 [ 4 55]]
[10 32 36 34  4 56]
[[[10 32]
  [36 34]]

 [[56 19]
  [75 20]]]


In [14]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr.flatten())
# changes any diemensional array into 1D array

[1 2 3 4 5 6]


Array Indexing

In [15]:
# Simple Slicing Works
# Normal as usual Indexing
# integer array indexing
arr = np.array([[10, 32, 36, 34], [125, 67, 84, 90], [45,72, 87.34, 4], [3, -9, 89, 34.67]])
index_arr = [[0, 1, 3], [3, 2, 0]]
print(arr[index_arr[0], index_arr[1]])

[34.000 84.000 3.000]


In [16]:
arr3d = np.array([
    [[1,2,3,4], [5,4,6,7], [2,3,4,6]],
    [[3,4,5,6], [5,6,7,8], [9,10,11,12]]
    ])
print(arr3d)
# print(arr3d[0][1][3] + arr3d[1][2][0])
print(arr3d[0,1,3] + arr3d[1,2,0])

[[[ 1  2  3  4]
  [ 5  4  6  7]
  [ 2  3  4  6]]

 [[ 3  4  5  6]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
16


In [17]:
arr3d = np.array([
    [[1,2,3,4], [5,4,6,7], [2,3,4,6]],
    [[3,4,5,6], [5,6,7,8], [9,10,11,12]]
    ])
arr = arr3d[arr3d >= 7]
print(arr, arr.ndim)

[ 7  7  8  9 10 11 12] 1


Operations

In [18]:
arr = np.array([[5, 215, 69], 
                [44, 74, 21], 
                [30, 12, 94]])
print(arr.max())
print(arr.max(axis = 1)) # Row-wise max
print(arr.max(axis = 0)) # column-wise max

# Similar for min()

print(arr.cumsum())
print(arr.cumsum(axis = 1))
print(arr.cumsum(axis = 0))

215
[215  74  94]
[ 44 215  94]
[  5 220 289 333 407 428 458 470 564]
[[  5 220 289]
 [ 44 118 139]
 [ 30  42 136]]
[[  5 215  69]
 [ 49 289  90]
 [ 79 301 184]]


In [19]:
arr1 = np.array([[5, 7], 
                 [8, 1]])
arr2 = np.array([[4, 1],
                 [9, 2]])

print(arr1 + arr2) # addition element-wise or matrix-addition
print(arr1 * arr2) # element-wise multiplication

print(arr1 @ arr2) # matrix multiplication
print(arr1.dot(arr2))

[[ 9  8]
 [17  3]]
[[20  7]
 [72  2]]
[[83 19]
 [41 10]]
[[83 19]
 [41 10]]


In [20]:
# converting datatype of existing array
arr = np.array([3, 6, 0, -1], dtype='i')
print(arr.dtype)

converted_arr = arr.astype('bool')
print(converted_arr)

int32
[ True  True False  True]


In [21]:
arr1 = np.array([[5, 7], 
                 [8, 1]])
arr2 = np.array([[4, 1],
                 [9, 2]])
print(np.concatenate((arr1, arr2), axis = 0)) # contenate along x-axis
print(np.concatenate((arr1, arr2), axis = 1)) # contenate along y-axis

[[5 7]
 [8 1]
 [4 1]
 [9 2]]
[[5 7 4 1]
 [8 1 9 2]]


## Note on `axis` :
The number of axis values = the dimensions
`axis = 0` => x-axis
`axis = 1` => y-axis
`axis = -1` => z-axis

In [22]:
arr = np.array([23, 45, 56, 88, 67, 22, 44, 66])
print(np.where(arr%2 == 1))

(array([0, 1, 4], dtype=int64),)


In [23]:
arr = np.array([23, 45, 56, 88, 67, 22, 44, 66])
split_arr = np.array_split(arr, 5)
print(split_arr)

[array([23, 45]), array([56, 88]), array([67, 22]), array([44]), array([66])]


In [24]:
arr = np.arange(36).reshape(6, 6)
print(arr)
print(np.hsplit(arr, 3))
# splitting sections must be factor of horizontal dimensions

print(np.vsplit(arr, 2))
# splitting sections must be factor of vertical dimensions

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[array([[ 0,  1],
       [ 6,  7],
       [12, 13],
       [18, 19],
       [24, 25],
       [30, 31]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15],
       [20, 21],
       [26, 27],
       [32, 33]]), array([[ 4,  5],
       [10, 11],
       [16, 17],
       [22, 23],
       [28, 29],
       [34, 35]])]
[array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]]), array([[18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])]


`3D splitting`

In [25]:
arr = np.arange(27).reshape(3,3,3)
print(arr)

# print(np.hsplit(arr, 3))
print(np.vsplit(arr, 3))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]]), array([[[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]]), array([[[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])]


V-Stack and H-Stack

In [27]:
arr1 = np.array([[1, 2],
                [3, 4]])
arr2 = np.array([[5, 6],
                [7, 8]])
arr3 = np.array([[9, 10], 
                [11, 12]])
arrvstack = np.vstack((arr1, arr2, arr3))
print(arrvstack)
print(np.vsplit(arrvstack, 3))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [29]:
arr1 = np.array([[1, 2],
                [3, 4]])
arr2 = np.array([[5, 6],
                [7, 8]])
arr3 = np.array([[9, 10], 
                [11, 12]])
arrhstack = np.hstack((arr1, arr2, arr3))
print(arrhstack)
print(np.hsplit(arrhstack, 3))

[[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


Array Addition works in:
- Arrays have exactly the same shape.
- Arrays have the same number of dimensions and the length of each dimension is either a common length or 1.
- Arrays having too few dimensions can have their shape prepended with a dimension of length so that the above stated property is true.