In [1]:
import numpy as np
import pandas as pd

In [2]:
dfx = pd.read_csv('./Book1.csv')
dfx

ID       name  class house color  marks
0    1     abcshd      3      yellow     21
1    2     akdasd      4         red     59
2    3   sahbhukc      4        blue     35
3    4   ahsjdgas      5        blue     65
4    5       jsad      3         red     12
5    6  asndkjshb      3        blue      6
6    7     asdasf      5      yellow     97
7    8       sdfd      5        blue     29
8    9      jtyhr      4        blue     80
9   10        fdg      4         red     71
10  11     bgfyer      4         red     78
11  12     xfftar      4      yellow     88
12  13     thgfdv      5        blue     74
13  14   hrtesfdc      3         red      5
14  15    ghnfgbr      3        blue     27
15  16      regsf      4        blue     99
16  17      rtsfx      3      yellow    100
17  18    rwsfdxc      3        blue      4
18  19       yhfg      3        blue     71
19  20     erasdz      3         red     11
20  21      trhfg      5         red    100
21  22       rsgf      4        blue     61
22  23     etrgsf      3        blue     23
23  24     t5ergf      5      yellow     56
24  25      qreaf      5        blue     85
25  26     ytehdg      3        blue      9
26  27        y6r      4      yellow     48
27  28    thrq3ea      5         red     79
28  29    4wrefsd      5      yellow     59
29  30       whsd      5      yellow      0

In [3]:
dfx = pd.DataFrame({'ID': [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30],
                   'name': ['a','s','g','d','fd','df','sd','fsd','cx','v','dfd','xdv','fg','fg','r','th','ynj','hg','b','cx','gfh','xf','ghh','ynj','tj','ghh','fy','jhy','gfhykj','fg'],
                   'class_1': [3,4,5,5,4,3,5,5,4,3,4,3,3,3,4,5,4,3,5,3,5,4,4,5,4,3,3,5,3,4],
                   'house': ['yellow','red','blue','red','yellow','blue','red','red','blue','yellow','blue','red','red','blue','red','yellow','red','blue','red','yellow','red','blue','red','red','yellow','blue','red','yellow','yellow','yellow'],
                   'marks': [70,72,91,35,55,40,20,50,58,42,58,40,100,54,46,51,47,38,21,32,27,53,50,53,67,6,81,67,39,10]})
dfx

ID    name  class_1   house  marks
0    1       a        3  yellow     70
1    2       s        4     red     72
2    3       g        5    blue     91
3    4       d        5     red     35
4    5      fd        4  yellow     55
5    6      df        3    blue     40
6    7      sd        5     red     20
7    8     fsd        5     red     50
8    9      cx        4    blue     58
9   10       v        3  yellow     42
10  11     dfd        4    blue     58
11  12     xdv        3     red     40
12  13      fg        3     red    100
13  14      fg        3    blue     54
14  15       r        4     red     46
15  16      th        5  yellow     51
16  17     ynj        4     red     47
17  18      hg        3    blue     38
18  19       b        5     red     21
19  20      cx        3  yellow     32
20  21     gfh        5     red     27
21  22      xf        4    blue     53
22  23     ghh        4     red     50
23  24     ynj        5     red     53
24  25      tj        4  yellow     67
25  26     ghh        3    blue      6
26  27      fy        3     red     81
27  28     jhy        5  yellow     67
28  29  gfhykj        3  yellow     39
29  30      fg        4  yellow     10

In [4]:
grp = dfx.groupby(by='class_1')
print(grp['marks'].agg([np.sum, np.average, np.count_nonzero, np.min, np.max]))

         sum    average  count_nonzero  amin  amax
class_1                                           
3        542  49.272727             11     6   100
4        516  51.600000             10    10    72
5        415  46.111111              9    20    91


In [5]:
grp = dfx.groupby(by=['class_1', 'house'])
print(grp['marks'].agg([np.mean, np.std, np.median, np.count_nonzero, np.min, np.max]))

                     mean        std  median  count_nonzero  amin  amax
class_1 house                                                          
3       blue    34.500000  20.289570    39.0              4     6    54
        red     73.666667  30.664855    81.0              3    40   100
        yellow  45.750000  16.700798    40.5              4    32    70
4       blue    56.333333   2.886751    58.0              3    53    58
        red     53.750000  12.284814    48.5              4    46    72
        yellow  44.000000  30.049958    55.0              3    10    67
5       blue    91.000000        NaN    91.0              1    91    91
        red     34.333333  14.361987    31.0              6    20    53
        yellow  59.000000  11.313708    59.0              2    51    67


In [6]:
grp = dfx.groupby(by='class_1')
print(grp.filter(lambda x: x['marks'].mean() >= 50))

    ID name  class_1   house  marks
1    2    s        4     red     72
4    5   fd        4  yellow     55
8    9   cx        4    blue     58
10  11  dfd        4    blue     58
14  15    r        4     red     46
16  17  ynj        4     red     47
21  22   xf        4    blue     53
22  23  ghh        4     red     50
24  25   tj        4  yellow     67
29  30   fg        4  yellow     10


In [7]:
table  = pd.pivot_table(dfx, values=['marks'], index=['class_1'], columns=['house'], aggfunc=[np.average, np.sum])
print(table)

           average                     sum            
             marks                   marks            
house         blue        red yellow  blue  red yellow
class_1                                               
3        34.500000  73.666667  45.75   138  221    183
4        56.333333  53.750000  44.00   169  215    132
5        91.000000  34.333333  59.00    91  206    118


# Numpy Practice

In [8]:
arr = np.array([45, 56, 78, 87, 98])
arr

array([45, 56, 78, 87, 98])

In [9]:
print(arr.ndim)

1


In [10]:
mat = np.zeros((3, 5))
print(mat)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
mat = np.zeros((3, 3), dtype='int')
print(mat)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [12]:
mat = np.ones((3, 3), dtype='i')*8
print(mat)

[[8 8 8]
 [8 8 8]
 [8 8 8]]


In [13]:
mat = np.array([['hello']*4]*4, dtype='str')
print(mat)

[['hello' 'hello' 'hello' 'hello']
 ['hello' 'hello' 'hello' 'hello']
 ['hello' 'hello' 'hello' 'hello']
 ['hello' 'hello' 'hello' 'hello']]


In [14]:
mat = np.full((4, 4), fill_value='hello', dtype='U5')
print(mat)
mat = np.full((4, 4), fill_value='hello', dtype='U4')
print(mat)

[['hello' 'hello' 'hello' 'hello']
 ['hello' 'hello' 'hello' 'hello']
 ['hello' 'hello' 'hello' 'hello']
 ['hello' 'hello' 'hello' 'hello']]
[['hell' 'hell' 'hell' 'hell']
 ['hell' 'hell' 'hell' 'hell']
 ['hell' 'hell' 'hell' 'hell']
 ['hell' 'hell' 'hell' 'hell']]


In [15]:
mat = np.random.rand(2,3)
print(mat)

[[0.32141777 0.83255412 0.96604966]
 [0.44021847 0.87626873 0.23221768]]


In [16]:
mat = np.random.randint(100, 200, size=(3,3,3))
print(mat)

[[[179 102 166]
  [196 129 137]
  [158 136 166]]

 [[188 137 168]
  [170 131 103]
  [124 193 147]]

 [[100 182 119]
  [159 196 123]
  [190 116 105]]]


In [17]:
# Generating a random normal distribution: N(mew, sigma)

mat = np.random.normal(0, 1, 3*3*3).reshape((3, 3, 3))
print(mat)

[[[-0.85574476 -1.13970623 -0.06725327]
  [ 0.78286124 -1.07756398 -1.5551205 ]
  [-0.09609291  0.47069993 -1.47034662]]

 [[-0.64446878  0.05028282 -0.04680063]
  [ 0.41727542  0.10600614  0.4698138 ]
  [-0.33115257 -1.27241465  0.96777785]]

 [[-0.88044589 -1.08647436  2.23066059]
  [ 0.19475421 -1.40740919  0.19152728]
  [ 0.11861584  1.01222948 -0.60518246]]]


In [18]:
arr = np.array([int(x) for x in range(5, 65, 5)])
print(arr)

[ 5 10 15 20 25 30 35 40 45 50 55 60]


In [19]:
arr = np.arange(5, 61, 5)
print(arr)

[ 5 10 15 20 25 30 35 40 45 50 55 60]


In [20]:
arr = [1,2,3,4,5]

pad_arr = np.pad(arr, pad_width=(3, 2),mode= 'constant', constant_values=(0, 7))
print(pad_arr)

[0 0 0 1 2 3 4 5 7 7]


In [21]:
arr = [1,2,3,4,5]

pad_arr = np.pad(arr, pad_width=(3, 2),mode= 'linear_ramp', end_values=(-4, 9))
print(pad_arr)

[-4 -3 -1  1  2  3  4  5  7  9]


In [22]:
mat = np.arange(0, 25).reshape((5, 5))
print(mat)

print(mat.flatten())
print(mat.ravel())

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [26]:
li = [2,2,5,7,1,4,2,9]
arr = np.array(li)

count = 0
for el in arr:
    if el == 2:
        count += 1
print(count)

3


In [28]:
print(np.datetime64('today', 'D'))
print(np.datetime64('today', 'D') - np.timedelta64(1, 'D'))
print(np.datetime64('today', 'D') + np.timedelta64(1, 'D'))

2022-12-30
2022-12-29
2022-12-31


In [32]:
dtype = [('name', 'U20'), ('class', int), ('height', float)]
students = [('Abhishek', 5, 48.5), ('Shreya', 6, 52.5),('Shruti', 5, 42.10), ('Vijay', 5, 40.11)]

students_arr = np.array(students, dtype=dtype)
print(students_arr)

[('Abhishek', 5, 48.5 ) ('Shreya', 6, 52.5 ) ('Shruti', 5, 42.1 )
 ('Vijay', 5, 40.11)]


In [33]:
arr = np.array([4, 0, 3, 6, 1, 9, 23, 5])
print(np.sort(arr)) # returns the sorted array
print(np.argsort(arr)) # returns the arguments of the sorted array

[ 0  1  3  4  5  6  9 23]
[1 4 2 0 7 3 5 6]


In [34]:
li1 = [3, 6, 1, 2]
li2 = [6, 4, 9, 3]

np.outer(li1, li2)

array([[18, 12, 27,  9],
       [36, 24, 54, 18],
       [ 6,  4,  9,  3],
       [12,  8, 18,  6]])

In [43]:
a = [4, 7, 3, 4]
b = [2, 8, 1, 6]

outer_prod = np.outer(a, b)

print(outer_prod)

print(outer_prod.ndim, outer_prod.shape)

sum = 0
for i in range(len(outer_prod)):
    sum += outer_prod[i][i]
print(sum)

print(outer_prod.diagonal().sum())

print(np.trace(outer_prod))

[[ 8 32  4 24]
 [14 56  7 42]
 [ 6 24  3 18]
 [ 8 32  4 24]]
2 (4, 4)
91
91
91


In [44]:
arr = np.arange(1, 17).reshape(4, 2, 2)
print(arr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]


In [45]:
arr = np.arange(4, 101, 4)
print(arr)

[  4   8  12  16  20  24  28  32  36  40  44  48  52  56  60  64  68  72
  76  80  84  88  92  96 100]


In [46]:
arr1 = np.arange(1, 11)
arr2 = np.arange(5, 16)

print(np.intersect1d(arr1, arr2))

[ 5  6  7  8  9 10]


In [48]:
arr = np.arange(0,51)

print(np.intersect1d(arr, np.arange(0, 21)))
print(arr[:21])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [51]:
arr = np.random.random((3, 3))

print(arr.max(), arr.min())

0.8406453657229027 0.165611081604622


In [55]:
arr = np.zeros((5, 5), dtype='i')
# print(arr)
pad_arr = np.pad(arr, (1, 1), 'constant', constant_values=(1))
print(pad_arr)

[[1 1 1 1 1 1 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 0 0 0 0 0 1]
 [1 1 1 1 1 1 1]]


In [67]:
arr = np.zeros((8, 8), dtype='i')

for i in range(8):
    if(i%2 == 0):
        start = 0
    else:
        start = 1
    while start < 8:
        arr[i][start] = 1
        start += 2
print(arr)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [69]:
arr = np.arange(0, 64)
arr = arr%2
arr = arr.reshape((8,8))

arr[[1,3,5,7]] = (arr[[1,3,5,7]]+1)%2
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [70]:
mat1 = np.random.randint(10, 20, 9).reshape((3,3,))
mat2 = np.random.randint(10, 20, 9).reshape((3,3,))

print(mat1 @ mat2) # matrix multiplication

[[821 835 837]
 [775 765 774]
 [771 761 784]]
